### ISSUE TITLE
RemoveField: RemoveField does not detect fields

### ISSUE THREAD

**Issue by MinaTahaei** [m-zakeri/CodART#15]
Tested on \CodART\testproject\input\src\main\java\org\json\JSONObject.java:

` my_listener = RemoveFieldRefactoringListener(common_token_stream=token_stream, class_identifier='JSONObject',
                                                 fieldname='NUMBER_PATTERN', filename=args.file)`

Error: Field "NUMBER_PATTERN" NOT FOUND (tested on a test field called N too)
File : remove_field/remove_field.py (main.py)

**Comment by seyyedaliayati** [comment]
It detects and delete field in remove_field_2.py, so we should use this file instead. Fixed in https://github.com/m-zakeri/CodART/commit/c951cdf359f46cafb000945dfceb8b5015938d6e
