### ISSUE TITLE
Increase Field Visibility

### ISSUE THREAD

**Issue by seyyedaliayati** [m-zakeri/CodART#18]
Parameters:
`
    udb_path = "/home/ali/Documents/compiler/Research/xerces2-j/xerces2-j3.udb"`
`    class_name = "ListNode"`
 `   field_name = "uri"
`

Problem:
It detects field and does the refactoring but doesn't propagate the changes! Look the following screenshots:

![Screenshot from 2021-02-23 23-58-58](https://user-images.githubusercontent.com/35001360/108904004-359fb200-7633-11eb-8d53-85cf7bce0d6a.png)
![Screenshot from 2021-02-23 23-59-04](https://user-images.githubusercontent.com/35001360/108904012-39cbcf80-7633-11eb-9bc7-afdbe98f3510.png)

**Comment by cpt9m0** [comment]
Related File Path:
refactorings/increase_field_visibility.py

**Comment by seyyedaliayati** [comment]
@m-zakeri Mr Shakeri is working on this.

**Comment by seyyedaliayati** [comment]
Moved to a new issue #107
