### ISSUE TITLE
file placement

### ISSUE THREAD

**Issue by armingh2000** [m-zakeri/CodART#2]
I think main.py and input.java files should come to the root folder due to the imports in main.py

```
from refactorings.encapsulate_field import EncapsulateFiledRefactoringListener
from refactorings.extract_class import ExtractClassRefactoringListener
from refactorings.gen.Java9_v2Lexer import Java9_v2Lexer
from refactorings.gen.Java9_v2Parser import Java9_v2Parser
```

The code above is the import section of main.py and each line imports from the refactorings folder which should be in the same hierarchy level as main.py . So if we move main.py and input.java to their parent folder this issue gets fixed. Otherwise, we should add root folder to system Path which is an unnecessary overdo.

**Comment by m-zakeri** [comment]
We are going to make a major update to use C++ as a backend for parsing Java source codes and also we will address your issue, ASAP.
