### ISSUE TITLE
Pull Up Constructor

### ISSUE THREAD

**Issue by ramtin-ehsani** [m-zakeri/CodART#48]
This refactor helps to make the code cleaner and moves the identical codes in the constructors to the parent.
For example:
```java
class Manager extends Employee {
  public Manager(String name, String id, int grade) {
    this.name = name;
    this.id = id;
    this.grade = grade;
  }
  // ...
}
```
and 
```java
class Admin extends Employee {
  public Admin(String name, String id, int grade) {
    this.name = name;
    this.id = id;
    this.grade = grade;
  }
  // ...
```
are the children of Employee and their constructors are similar. So:
```java
class Manager extends Employee {
  public Manager(String name, String id, int grade) {
    super(name, id, grade);
  }
  // ...
}
```
and the parent class:
```java
class Employee {
  public Employee(String name, String id, int grade) {
    this.name = name;
    this.id = id;
    this.grade = grade;
  }
  // ...
}
```

**Comment by m-zakeri** [comment]
Ok! What is the problem/issue with this refactoring?

> 
> 
> This refactor helps to make the code cleaner and moves the identical codes in the constructors to the parent.
> For example:
> 
> ```java
> class Manager extends Employee {
>   public Manager(String name, String id, int grade) {
>     this.name = name;
>     this.id = id;
>     this.grade = grade;
>   }
>   // ...
> }
> ```
> 
> and
> 
> ```java
> class Admin extends Employee {
>   public Admin(String name, String id, int grade) {
>     this.name = name;
>     this.id = id;
>     this.grade = grade;
>   }
>   // ...
> ```
> 
> are the children of Employee and their constructors are similar. So:
> 
> ```java
> class Manager extends Employee {
>   public Manager(String name, String id, int grade) {
>     super(name, id, grade);
>   }
>   // ...
> }
> ```
> 
> and the parent class:
> 
> ```java
> class Employee {
>   public Employee(String name, String id, int grade) {
>     this.name = name;
>     this.id = id;
>     this.grade = grade;
>   }
>   // ...
> }
> ```

**Comment by ramtin-ehsani** [comment]
> 
> 
> Ok! What is the problem/issue with this refactoring?
> 
> > This refactor helps to make the code cleaner and moves the identical codes in the constructors to the parent.
> > For example:
> > ```java
> > class Manager extends Employee {
> >   public Manager(String name, String id, int grade) {
> >     this.name = name;
> >     this.id = id;
> >     this.grade = grade;
> >   }
> >   // ...
> > }
> > ```
> > 
> > 
> >   
> >     
> >     
> >   
> > 
> > 
> > and
> > ```java
> > class Admin extends Employee {
> >   public Admin(String name, String id, int grade) {
> >     this.name = name;
> >     this.id = id;
> >     this.grade = grade;
> >   }
> >   // ...
> > ```
> > 
> > 
> >   
> >     
> >     
> >   
> > 
> > 
> > are the children of Employee and their constructors are similar. So:
> > ```java
> > class Manager extends Employee {
> >   public Manager(String name, String id, int grade) {
> >     super(name, id, grade);
> >   }
> >   // ...
> > }
> > ```
> > 
> > 
> >   
> >     
> >     
> >   
> > 
> > 
> > and the parent class:
> > ```java
> > class Employee {
> >   public Employee(String name, String id, int grade) {
> >     this.name = name;
> >     this.id = id;
> >     this.grade = grade;
> >   }
> >   // ...
> > }
> > ```

It's not an issue. It's a feature request
