### ISSUE TITLE
Extract Method: Does not create a new method!

### ISSUE THREAD

**Issue by seyyedaliayati** [m-zakeri/CodART#69]
**Describe the bug**
I created a class called ExtractMethod:
src/ExtractMethod.java:
```
public class ExtractMethod {

    String name = "Ali";

    void printBanner() {
        System.out.println("ExtractMethod.printBanner()");
    }

    int getOutstanding(){
        return 334;
    }

    void printOwing() {
        printBanner();

        // Print details.
        System.out.println("name: " + this.name);
        System.out.println("amount: " + getOutstanding());
    }
}
```
I want to extract lines 17 and 18 (including println calls) into a new method called printDetails, so I set the configuration like this:
```
_conf = {
        'target_package': '',
        'target_file': "/home/ali/Desktop/JavaTestProject/src/ExtractMethod.java",
        'output_file': "/home/ali/Desktop/JavaTestProject/src/ExtractMethod.java",
        'target_class': 'ExtractMethod',
        'target_method': 'printOwing',
        # which lines of source code to extract
        # todo: after smell detection in phase 2 , we'll get a list of lines automatically
        'lines': [17, 18, ],
        'new_method_name': 'printDetails',
    }
```
But After running the script I got this:
```
public class ExtractMethod {

    String name = "Ali";

    void printBanner() {
        System.out.println("ExtractMethod.printBanner()");
    }

    int getOutstanding(){
        return 334;
    }

    void printOwing() {
        printBanner();

        // Print details.
		printDetails();
    }
}
```
As you can see it successfully detected lines 17 and 18 and replaced them with a new method call **but there is no printDetails!**

**File Path**
refactorings/extract_method.py

**Group**
@sinaziaee

**Comment by 9Knight9n** [comment]
Hi 
just checked code and there was some problem with test cases which are not in package.
bug is resolved now.

there was also some problems with your conf object.
1.if package name is not important or is unknown enter None for its value.
2.lines are calculated from beginning of method you are willing to extract counting from 0.
these conditions are now mentioned at beginning of extract method class.
so your conf object should be something like:
_conf = {
        'target_package': None,
        'target_file': "/home/ali/Desktop/JavaTestProject/src/ExtractMethod.java",
        'output_file': "/home/ali/Desktop/JavaTestProject/src/ExtractMethod.java",
        'target_class': 'ExtractMethod',
        'target_method': 'printOwing',
        'lines': [4, 5],
        'new_method_name': 'printDetails',
}

thank you for your notices.

**Comment by seyyedaliayati** [comment]
I merged your pull request but there is a problem:
There is an example in https://refactoring.guru/extract-method
But after applying your extract method the output differs from this. Why?
In this example it is not a bug but it can be sometimes!

In the example we have:
```
void printOwing() {
  printBanner();
  printDetails(getOutstanding());
}

void printDetails(double outstanding) {
  System.out.println("name: " + name);
  System.out.println("amount: " + outstanding);
}
```

After running refactorings/extract_method.py we get:
```
void printOwing() {
        printBanner();

        printDetails();
    }

    public void printDetails() {
        // Print details.
        System.out.println("name: " + name);
        System.out.println("amount: " + getOutstanding());
    }
```

**Comment by sadeghjafari5528** [comment]
I thing is not a good idea to make a variable for each method that call in this method . I suggest that detect dependency of this method(getOutstanding()) and write a suitable import statement in destination file ( if we extract method and move it in another file ) to handle this issue.
I suggest this solution because of :
    1. if we call a large number of methods in our code we dealing with lots of input parameters.
    2. if our called method parameters were local variables we should not fallowing your idea
