### ISSUE TITLE
Handle static and private for move method

### ISSUE THREAD

**Issue by seyyedaliayati** [m-zakeri/CodART#83]
**Describe the bug**
When we move a method to a new class we should take care of the variable and methods used in that method specially if they are private or static!

**To Reproduce**
Steps to reproduce the behavior try to move "getNumber2" in a target class:
![image](https://user-images.githubusercontent.com/35001360/122912550-afd80d00-d36d-11eb-8c2d-54d681c501d7.png)

**Comment by seyyedaliayati** [comment]
@pouorix

**Comment by pouorix** [comment]
> @pouorix
Done...
for private using printed in terminal : The target method is using the private variable , so cannot refactoring
and for static using write Source.number instance of {instance_name}.number
pull request : https://github.com/m-zakeri/CodART/pull/98
